### ISSUE TITLE
Percentage signs not shown in an article

### ISSUE THREAD

**Issue by silvia-br** [serlo/backlog#117] opened 2023-05-15 15:42 UTC
**Description**
In an article, two percentage signs are not shown (not reproducible).

**Links**
Page with bug: https://de.serlo.org/mathe/21332/21332

**Screenshot/Video**
Richtige Version (z.B. bei Silvia):
![image](https://github.com/serlo/backlog/assets/127129431/0296bd4f-2024-4387-bf32-6887100c6301)

Falsche Version (bei Beate):
![image](https://github.com/serlo/backlog/assets/127129431/b2def0d7-735f-42f2-a1cf-6cfad1da6b8f)

**Reproducible?**
No

**Betriebssystem and Browser (incl. Version)**
Browser: Firefox Version 112.0.2 (64Bit)

**Error message from the browser console**
n/a

**Stakeholder**
Beate Pauly (per Email an Peter)

**Trello-Card**
https://trello.com/c/rmjiTSEP/135-bug-percentage-signs-not-shown-in-text

**Comment by kulla** [comment] 2023-05-15 19:37
I cannot reproduce it -> Thus we cannot do something and I would close it and ask for more context when this bug occurs again.

**Comment by silvia-br** [comment] 2023-05-16 12:14
Isn't it better to leave it open? For me closed = solved, which is not the case for this bug.
I know that we cannot reproduce it and solve it now and that's why we have the backlog, so this bug is here as "reminder" for the future. If we receive more info about this or another author has the same problem, we can easily find the issue again and look at it. If we close this and in the future it happens again, then we have to look at the "closed" issues, which is less obvious for me.

**Comment by elbotho** [comment] 2023-05-16 12:21
<img width="315" alt="image" src="https://github.com/serlo/backlog/assets/1258870/c0d1cc58-73ea-4fac-8d38-9b00076cda48">

**Closed as not planned** 2023-05-16 12:48 UTC
Labels: bug, text-plugin
